<script setup lang="ts">
import { inject, onMounted, ref, type Ref } from "vue";
import { api, jsonBody } from "../api";
const user=inject<Ref<any>>("adminUser")!;const users=ref<any[]>([]),clients=ref<any[]>([]),events=ref<any[]>([]),metrics=ref<any>(null),oneTimeKey=ref(""),error=ref("");
const newUser=ref({username:"",password:"",role:"viewer"}),newClient=ref({name:"",scopes:"reports:write,advisor:write",rate_limit_per_minute:60,expires_at:""});
async function load(){metrics.value=await api("/api/v1/admin/metrics/summary");if(user.value.role!=="curator"){const a=await api<any>("/api/v1/admin/audit-events");events.value=a.events;}if(user.value.role==='admin'){const u=await api<any>("/api/v1/admin/users");users.value=u.users;const c=await api<any>("/api/v1/admin/api-clients");clients.value=c.api_clients;}}
async function createUser(){await api("/api/v1/admin/users",{method:"POST",body:jsonBody(newUser.value)});newUser.value={username:"",password:"",role:"viewer"};await load();}
async function createClient(){const body={name:newClient.value.name,scopes:newClient.value.scopes.split(',').map(x=>x.trim()).filter(Boolean),rate_limit_per_minute:newClient.value.rate_limit_per_minute,expires_at:newClient.value.expires_at?new Date(newClient.value.expires_at).toISOString():null};const result=await api<any>("/api/v1/admin/api-clients",{method:"POST",body:jsonBody(body)});oneTimeKey.value=result.api_key;await load();}
async function revoke(id:string){await api(`/api/v1/admin/api-clients/${id}/revoke`,{method:"POST"});await load();}
async function toggleUser(row:any){await api(`/api/v1/admin/users/${row.id}`,{method:"PATCH",body:jsonBody({active:!row.active})});await load();}
async function changeRole(row:any){await api(`/api/v1/admin/users/${row.id}`,{method:"PATCH",body:jsonBody({role:row.role})});await load();}
onMounted(()=>load().catch(e=>error.value=e.message));
</script>
<template><h1 class="page-title">访问与审计</h1><div class="alert">指标和审计不保存原始血压、用户画像、对话正文或外部 API 密钥。</div><div v-if="error" class="error">{{error}}</div>
  <section class="card"><h3>匿名运行指标</h3><pre class="code">{{JSON.stringify(metrics,null,2)}}</pre></section>
  <div v-if="user.role==='admin'" class="grid two" style="margin-top:14px"><section class="card"><h3>本地账号 RBAC</h3><table><tbody><tr v-for="row in users" :key="row.id"><td>{{row.username}}</td><td><select class="input" v-model="row.role" :disabled="row.id===user.id" @change="changeRole(row)"><option>admin</option><option>curator</option><option>reviewer</option><option>viewer</option></select></td><td><button class="btn" :disabled="row.id===user.id" @click="toggleUser(row)">{{row.active?'停用':'启用'}}</button></td></tr></tbody></table><div class="form-grid" style="margin-top:10px"><label>用户名<input class="input" v-model="newUser.username" /></label><label>角色<select class="input" v-model="newUser.role"><option>admin</option><option>curator</option><option>reviewer</option><option>viewer</option></select></label><label class="span-2">初始密码（12+）<input class="input" type="password" v-model="newUser.password" /></label></div><button class="btn primary" @click="createUser">创建账号</button></section>
  <section class="card"><h3>小程序 API Clients</h3><div v-if="oneTimeKey" class="alert"><strong>仅显示一次：</strong><code>{{oneTimeKey}}</code></div><table><tbody><tr v-for="row in clients" :key="row.id"><td>{{row.name}}<br><code>{{row.key_prefix}}…</code></td><td>{{row.scopes.join('、')}}<br><span class="muted">{{row.rate_limit_per_minute}}/min · 到期 {{row.expires_at||'无'}}</span></td><td><button class="btn danger" v-if="row.active" @click="revoke(row.id)">吊销</button></td></tr></tbody></table><div class="form-grid"><label>名称<input class="input" v-model="newClient.name" /></label><label>每分钟限速<input class="input" type="number" min="1" v-model.number="newClient.rate_limit_per_minute" /></label><label class="span-2">Scopes（逗号）<input class="input" v-model="newClient.scopes" /></label><label class="span-2">到期时间（可选）<input class="input" type="datetime-local" v-model="newClient.expires_at" /></label></div><button class="btn primary" style="margin-top:8px" @click="createClient">创建 Client Key</button></section></div>
  <section v-if="user.role!=='curator'" class="card" style="margin-top:14px"><h3>操作审计</h3><table><thead><tr><th>时间</th><th>操作者</th><th>动作</th><th>资源</th><th>结果</th></tr></thead><tbody><tr v-for="row in events" :key="row.id"><td>{{row.created_at}}</td><td>{{row.actor_name}}</td><td>{{row.action}}</td><td>{{row.resource_type}} / {{row.resource_id}}</td><td><span class="badge" :class="row.status==='success'?'current':'failed'">{{row.status}}</span></td></tr></tbody></table></section><section v-else class="card" style="margin-top:14px"><p class="muted">策展角色可查看匿名运行指标；账号、Client 与操作审计由管理员或审阅角色查看。</p></section>
</template>
