<script setup lang="ts">
import { computed, inject, onMounted, ref, type Ref } from "vue";
import { api, jsonBody } from "../api";
const user=inject<Ref<any>>("adminUser")!;
const configs=ref<any[]>([]), drafts=ref<any[]>([]), revisions=ref<any[]>([]), selectedKey=ref(""), editor=ref(""), reason=ref(""), error=ref(""), message=ref("");
const selected=computed(()=>configs.value.find(x=>x.key===selectedKey.value));
async function load(){ const [c,d,r]=await Promise.all([api<any>("/api/v1/admin/configs"),api<any>("/api/v1/admin/config-drafts"),api<any>("/api/v1/admin/config-revisions")]);configs.value=c.configs;drafts.value=d.drafts;revisions.value=r.revisions;if(!selectedKey.value&&configs.value.length)select(configs.value[0].key); }
function select(key:string){selectedKey.value=key;const row=configs.value.find(x=>x.key===key);editor.value=JSON.stringify(row.content,null,2);}
async function makeDraft(){try{const row=await api<any>(`/api/v1/admin/configs/${selectedKey.value}/drafts`,{method:"POST",body:jsonBody({content:JSON.parse(editor.value),reason:reason.value||null})});message.value=`草稿 ${row.id} 已创建`;await load();}catch(e){error.value=(e as Error).message;}}
async function validate(id:string){try{const result=await api<any>(`/api/v1/admin/config-drafts/${id}/validate`,{method:"POST"});message.value=`候选配置校验任务 ${result.job.id} 已排队`;await load();}catch(e){error.value=(e as Error).message;}}
async function publish(row:any){const why=prompt("发布原因",reason.value||"经管理员确认发布");if(!why)return;try{await api(`/api/v1/admin/config-drafts/${row.id}/publish`,{method:"POST",headers:{"If-Match":row.base_revision},body:jsonBody({reason:why,expected_revision:row.base_revision,confirmation:row.config_key})});message.value="配置已原子发布并刷新缓存";await load();select(row.config_key);}catch(e){error.value=(e as Error).message;}}
async function rollback(row:any){const why=prompt(`回滚 ${row.config_key} 到 ${row.revision} 的原因`);if(!why)return;const current=configs.value.find(x=>x.key===row.config_key);if(!current){error.value="找不到当前配置 revision";return;}try{const result=await api<any>(`/api/v1/admin/config-revisions/${row.id}/rollback`,{method:"POST",headers:{"If-Match":current.revision},body:jsonBody({reason:why})});message.value=`安全回滚任务 ${result.job.id} 已排队`;await load();}catch(e){error.value=(e as Error).message;}}
onMounted(()=>load().catch(e=>error.value=e.message));
</script>
<template><h1 class="page-title">配置中心</h1><div class="alert">医学规则配置采用草稿 → 差异 → 隔离回归 → 管理员确认 → 原子发布；核心医疗安全边界不可关闭。</div><div v-if="error" class="error">{{error}}</div><div v-if="message" class="alert">{{message}}</div>
  <div class="grid two"><section class="card"><h3>当前已发布配置</h3><div class="tabs"><button class="btn" v-for="row in configs" :key="row.key" @click="select(row.key)">{{row.key}} <span class="badge" :class="row.risk_level==='high'?'stale':'current'">{{row.risk_level}}</span></button></div><div v-if="selected"><div class="muted">revision {{selected.revision}} · 影响：{{selected.read_by}}</div><textarea class="input" style="min-height:520px" v-model="editor" :disabled="user.role!=='admin'"></textarea><template v-if="user.role==='admin'"><label>变更原因<input class="input" v-model="reason" /></label><button class="btn primary" style="margin-top:10px" @click="makeDraft">创建配置草稿</button></template></div></section>
  <section class="card"><h3>草稿与发布</h3><div v-for="row in drafts" :key="row.id" style="border-bottom:1px solid #e4eaf2;padding:10px 0"><strong>{{row.config_key}}</strong> <span class="badge" :class="row.status">{{row.status}}</span><div class="muted">基于 {{row.base_revision}}</div><div class="danger" v-if="row.validation?.errors?.length">{{row.validation.errors.join('；')}}</div><div class="toolbar" style="margin-top:6px" v-if="user.role==='admin'"><button class="btn" v-if="!['published','validating'].includes(row.status)" @click="validate(row.id)">校验、固定病例与回归</button><button class="btn primary" v-if="row.status==='validated'" @click="publish(row)">确认发布</button></div><details><summary>差异</summary><pre class="code">{{row.diff}}</pre></details><details v-if="Object.keys(row.validation||{}).length"><summary>验证结果</summary><pre class="code">{{JSON.stringify(row.validation,null,2)}}</pre></details></div></section></div>
  <section class="card" style="margin-top:14px"><h3>发布历史与回滚</h3><table><thead><tr><th>配置</th><th>Revision</th><th>发布人 / 时间</th><th>原因</th><th>操作</th></tr></thead><tbody><tr v-for="row in revisions" :key="row.id"><td>{{row.config_key}}</td><td><code>{{row.revision}}</code></td><td>{{row.published_by}}<br><span class="muted">{{row.created_at}}</span></td><td>{{row.reason}}</td><td><button v-if="user.role==='admin'" class="btn" @click="rollback(row)">安全校验后回滚</button></td></tr></tbody></table></section>
</template>
