<script setup lang="ts">
import { inject, onMounted, ref, type Ref } from "vue";
import { api, jsonBody } from "../api";
const user=inject<Ref<any>>("adminUser")!;const rows=ref<any[]>([]), secrets=ref<Record<string,string>>({}), settings=ref<Record<string,string>>({}), results=ref<Record<string,any>>({}), error=ref("");
async function load(){const result=await api<any>("/api/v1/admin/integrations");rows.value=result.integrations;for(const row of rows.value)settings.value[row.channel]=JSON.stringify(row.settings||{},null,2);}
async function save(row:any){try{row.settings=JSON.parse(settings.value[row.channel]||"{}");await api(`/api/v1/admin/integrations/${row.channel}`,{method:"PUT",body:jsonBody(row)});await load();}catch(e){error.value=(e as Error).message;}}
async function saveSecret(channel:string){try{await api(`/api/v1/admin/integrations/${channel}/secret`,{method:"PUT",body:jsonBody({secret:secrets.value[channel]})});secrets.value[channel]="";await load();}catch(e){error.value=(e as Error).message;}}
async function test(row:any){results.value[row.channel]=await api(`/api/v1/admin/integrations/${row.channel}/test`,{method:"POST"});}
onMounted(()=>load().catch(e=>error.value=e.message));
</script>
<template><h1 class="page-title">外部 API 集成</h1><div class="alert">四个通道凭证严格隔离；连通测试仅发送固定合成文本。评估通道 send_fulltext 在 V1 固定为 false。</div><div v-if="error" class="error">{{error}}</div>
  <div class="grid two"><section class="card" v-for="row in rows" :key="row.channel"><h3>{{row.channel}} <span class="badge" :class="row.enabled?'current':'missing'">{{row.enabled?'启用':'停用'}}</span></h3><div class="form-grid"><label>Provider<input class="input" v-model="row.provider" :disabled="user.role!=='admin'" /></label><label>Model<input class="input" v-model="row.model" :disabled="user.role!=='admin'" /></label><label class="span-2">Base URL<input class="input" v-model="row.base_url" :disabled="user.role!=='admin'" /></label><label>超时秒<input class="input" type="number" v-model.number="row.timeout_sec" :disabled="user.role!=='admin'" /></label><label>最大并发<input class="input" type="number" v-model.number="row.max_concurrency" :disabled="user.role!=='admin'" /></label><label><input type="checkbox" v-model="row.enabled" :disabled="user.role!=='admin'" /> 启用</label><label class="span-2">通道参数 JSON（evaluation.send_fulltext 固定 false）<textarea class="input" v-model="settings[row.channel]" :disabled="user.role!=='admin'"></textarea></label></div><div class="toolbar" style="margin-top:10px" v-if="user.role==='admin'"><button class="btn" @click="save(row)">保存连接配置</button><button class="btn" @click="test(row)">合成请求测试</button></div><div v-if="row.channel!=='crossref' && user.role==='admin'"><label class="muted">API Key（{{row.secret_configured?'已配置，永不回显':'未配置'}}）</label><div class="toolbar"><input class="input" type="password" v-model="secrets[row.channel]" placeholder="输入新密钥进行写入/轮换" /><button class="btn primary" :disabled="!secrets[row.channel]" @click="saveSecret(row.channel)">加密保存</button></div></div><pre v-if="results[row.channel]" class="code">{{JSON.stringify(results[row.channel],null,2)}}</pre></section></div>
</template>
